### ISSUE TITLE
Sheet 8 with solutions

### ISSUE THREAD

**Issue by gloriamontana** [JointPhysicsAnalysisCenter/MTHS-Material#44]
\documentclass[a4paper,11pt]{article}
\usepackage{style/preamble}
% \titleformat{\subsection}[runin]{}{}{}{}[]
\renewcommand*{\thesection}{\Roman{section}}
\renewcommand*{\thesubsection}{\alph{subsection})}
\renewcommand*{\thesubsubsection}{\roman{subsubsection}}

\begin{document}

\section{Reggeization and Unitarity} 

Van Hove \cite{vanHove:1967zz} proposed a physically intuitive picture of a Reggeon by relating it to Feynman diagrams in the cross-channels. We will explore this picture of Reggeization with a simple model.

\subsection{Elementary $t$-channel exchanges}
Consider the amplitude corresponding to a particle with spin-$J$ and mass $m_J$  exchanged in the $t$-channel as:
%%
    \begin{equation}   
        \label{eq:AJ}
        A^J(s,t) = i \, g_J \, \left( q_1^{\mu_1} \dots q_1^{\mu_J} \right) \frac{P^J_{\mu_1\dots\mu_J,\nu_1\dots\nu_J}(k)}{m_J^2 - t} \left( q_{\bar{2}}^{\nu_1} \dots q_{\bar{2}}^{\nu_J} \right) 
    \end{equation}
%%
where $g_J$ is a coupling constant with dimension $2-2J$ (i.e., $A^J(s,t)$ is dimensionless) and the projector of spin-$J$ is defined from the polarization tensor of rank-$J\geq1$ as
%%
    \begin{equation}
        P^J_{\mu_1\dots\mu_J,\nu_1\dots\nu_J}(k) = \frac{(J+1)}{2} \, \sum_{\lambda} 
         \epsilon^{\mu_1\dots\mu_J}(k,\lambda) \, \epsilon^{*\nu_1\dots\nu_J}(k,\lambda) ~.
    \end{equation}
%%

Using the exchange momentum $k = q_1 + q_{\bar{3}} = q_1 - q_3$, calculate the amplitudes corresponding to $J=0,1,2$ exchanges in terms of $t= k^2$, the modulus of 3-momentum and cosine of scattering angle in the $t$-channel frame, $q_t$ and $\cos\theta_t$ respectively. Use the explicit forms of the projectors:
%%
    \begin{gather}
        P^0(k^2) = 1 \\
        P^1_{\mu\nu}(k^2) \equiv \tilde{g}_{\mu\nu} =   \frac{ k_\mu \, k_\nu}{ k^2} - g_{\mu\nu}\\ 
        P^2_{\mu\nu\alpha\beta}(k^2) = \frac{3}{4}\left(\tilde{g}_{\mu\alpha} \, \tilde{g}_{\nu\beta} + \tilde{g}_{\mu\beta} \, \tilde{g}_{\nu\alpha}\right) - \frac{1}{2} \, \tilde{g}_{\mu\nu} \, \tilde{g}_{\alpha\beta} ~,
    \end{gather}
%%
and conjecture a generalization of the amplitude for arbitrary integer $J$. 

\noindent\textit{Hint: Show that in the $t$-channel frame, the exchange particle is at rest and therefore $\tilde{g}_{\mu\nu}$ reduces to a $\delta_{ij}$ with respect to only spacial momenta.} 

\subsection{Unitarity vs Elementary exchanges}
Express the amplitude entirely in terms of invariants $s$ and $t$. Use the optical theorem to relate the elastic amplitude to a total hadronic cross section:
\begin{equation}
    \sigma_\text{tot} = \frac{1}{2q\sqrt{s}} \, \Im A^J(s,t=0)~.
\end{equation}
Unitarity (via the Froissart-Martin bound) prohibits $\sigma_\text{tot}$ from growing faster than $\log^2 s$ as $s\to\infty$~. What is then the maximal spin a single elementary exchange can have while satisfying this bound? Why is this a problem?

\subsection{Van Hove Reggeon} 

Consider an amplitude of the form 
%%
    \begin{equation}
        \label{eq:vanhove}
        A(s,t) = \sum_{J=0}^\infty g \, r^{2J} \, \frac{ (q_t^2 \, \cos\theta_t)^J}{J- \alpha(t)} ~.
    \end{equation}
%%
Here $\alpha(t) = \alpha(0) + \alpha^\prime \, t$ is a real, linear Regge trajectory, $g$ is a dimensionless coupling constant and $r \sim 1$ fm is a range parameter. 
Compare \cref{eq:vanhove} with \cref{eq:AJ}, write the mass of the $J$th pole, $m_J^2$, as a function of the Regge parameters $\alpha(0)$ and $\alpha^\prime$. Interpret the pole structure in terms of the spectrum of particles in the model. 
\\

\noindent If the sum is truncated to a finite $J_\text{max}$, and we take the $s\to \infty$ limit, what is the high energy behavior of the amplitude? 

\subsection{Analytic continuation in $J$}
Show that if the summation is kept infinite, the amplitude can be re-summed to something that is entirely analytic in $s$, $t$, $u$, and $J$. 

\noindent \textit{Hint: Use the Mellin transform
%%
    \begin{equation}
        \frac{1}{J-\alpha(t)} = \int_0^1 dx \, x^{J-\alpha(t) - 1} ~,
    \end{equation}
%%
to express the amplitude in terms of the Gaussian hypergeometric function and the Euler Beta function
%%
    \begin{equation}
        B(b, c-b) \, _2F_1(1, b, c; z) =  \int_0^1 dx \, \frac{ x^{b-1} \, (1-x)^{c-b-1}}{1-x \, z} ~. 
    \end{equation}
%%
}
\subsection{Unitarity vs Reggeized exchanges}
Revisit $\mathbf{b)}$ with the resummed amplitude. Take the $s\to\infty$ limit and set a limit on the maximal intercept $\alpha(0)$ which is allowed by unitarity.  

\noindent \textit{Hint: Assume that $\alpha(0) > -1$ and use the asymptotic behavior of the hypergeometric function given by 
%%
    \begin{equation}
        _2F_1(1,b,c;z) \to \frac{\Gamma(c)\,\Gamma(1-b)}{\Gamma(1) \,\Gamma(c-b)} \, (-z)^{-b}  ~.
    \end{equation}
%%
}

\subsection{The Reggeon ``propagator"}
Modify \cref{eq:AJ} to have a definite signature by defining
%%
    \begin{equation}
        A^{\pm}(s,t) = \frac{1}{2}\left[A(s,t) \pm A(u,t) \right]~.
    \end{equation}
%%
Repeat $\textbf{d)}$ and  $\textbf{e)}$ with this signatured amplitude. Compare with the canonical form of the Reggeon exchange:
%%
    \begin{equation}
        A^\pm_\mathbb{R}(s,t) = \beta(t) \, \frac{1}{2}\left[\pm1 + e^{-i\pi\alpha(t)}\right] \, \Gamma(-\alpha(t)) \, \left(\frac{s}{s_0}\right)^{\alpha(t)} ~.
    \end{equation}
%%
Identify the Regge residue $\beta(t)$ and characteristic scale $s_0$ in terms of the parameters $g_0$ and $r$. 

\section{Veneziano Amplitude}

The quintessential dual amplitude was first proposed by Veneziano for $\omega\to3\pi$ \cite{Veneziano:1968yb} and later applied to elastic $\pi\pi$ scattering by Shapiro \cite{Shapiro:1969km} and Lovelace \cite{Lovelace:1968kjy}. Consider the $\pi^+\pi^-$ scattering amplitude of the form
%%
    \begin{equation}
        \label{eq:Astu}
        \mathcal{A}(s,t,u) = V(s,t) + V(s,u) - V(t,u) ~.
    \end{equation}
%%
with each 
%%
    \begin{equation}   
        \label{eq:Fst}
        V(s,t) = \frac{\Gamma(1-\alpha(s)) \, \Gamma(1-\alpha(t))}{\Gamma(1-\alpha(s) - \alpha(t))} ~,
    \end{equation}
%%
where $\alpha(s) = \alpha(0) + \alpha^\prime s$ is a real, linear Regge trajectory with $\alpha^\prime > 0$. 

\subsection{Duality} 
Show that the function $V(s,t)$ is symmetric in $s\leftrightarrow t$ and dual, i.e., it can be written entirely as a sum of either $s$-channel poles OR $t$-channel poles but never both simultaneously. Compare with the Reggeized amplitude in the previous problem, was that amplitude dual?

\noindent \textit{Hint: Relate $V(s,t)$ to the Euler Beta function
    \begin{equation}
        B(x,y) = \frac{\Gamma(x) \, \Gamma(y)}{\Gamma(x+y)}
    \end{equation}
and use the identities $B(x,y) = B(y,x)$ and
%%
    \begin{equation}
        B(p-x, q-y) = \sum_{J=1}^\infty \, \frac{\Gamma(J-p+1 +x)}{\Gamma(J) \, \Gamma(-p + 1 +x)} \, \frac{1}{J-1+q-y} ~.
    \end{equation}
%%
}

\subsection{Isospin basis} 
Define the $s$-channel isospin basis through
%%
    \begin{equation}
        \begin{pmatrix}
            \mathcal{A}^{(0)}(s,t,u) \\
            \mathcal{A}^{(1)}(s,t,u) \\
            \mathcal{A}^{(2)}(s,t,u)             
        \end{pmatrix}
        = 
        \frac{1}{2}\begin{pmatrix}
            3 & 1 & 1 \\
            0 & 1 & -1 \\
            0 & 1 & 1 
        \end{pmatrix}
        \begin{pmatrix}
            \mathcal{A}(s,t,u) \\
            \mathcal{A}(t,s,u) \\
            \mathcal{A}(u,t,s)              
        \end{pmatrix}
        ~.
    \end{equation}
%%
Write down the definite-isospin amplitudes in terms of $V$'s. Comment on the symmetry properties of each isospin amplitude with respect to $t \leftrightarrow u$. 

\subsection{Chew-Frautshi plot}
Locate where each $\mathcal{A}^{(I)}(s,t,u)$ will have poles in the $s$-channel physical region. What is their residue? Draw a schematic Chew-Frautschi plot of the resonance spectrum in each isospin channel.

\subsection{Regge limit}
Now consider the limit $t \to \infty$ and $u \to - \infty$ with $s \leq 0$ is fixed. What is the asymptotic behavior of $V(s,t)$ and $V(s,u)$? Assume that $V(t,u)$ vanishes faster than any power of $s$ in this limit. What is the resulting behavior of the isospin amplitudes $\mathcal{A}^{(I)}(s,t,u)$ in this limit?

\noindent \textit{ Hint: Use the Sterling approximation of the $\Gamma$ function., i.e. as $|x|\to \infty$
    \begin{equation}
        \Gamma(x) \to \sqrt{\frac{2\pi}{x}} \left( \frac{x}{e} \right)^x ~.
    \end{equation}
}

\subsection{Ancestors and Strings}
Consider the model now with a complex trajectory $\alpha(s) = a_0 + \alpha^\prime \, s + i \,\Gamma$ with $\Gamma > 0$ to move the poles off the real axis. Reexamine the the Chew-Frautshi plot for the $I=1$ amplitude using this trajectory, why is the resulting spectrum problematic? Try a real but non-linear trajectory, say $\alpha(s) = \alpha_0 + \alpha^\prime \, s + \alpha^{\prime\prime} \, s^2$, what is the spectrum like now?

Compare the requirements of the trajectory for $V(s,t)$ to make sense with the energy levels of a rotating relativistic string with a string tension $T$:
%%
    \begin{equation}
        E_J^2 = \frac{1}{2\pi \, T} \, J ~.
    \end{equation}
%%
What is a possible microscopic picture of hadrons if the Veneziano amplitude is believed? 

\section{Sommerfeld-Watson Transform} 

\subsection{Geometric series}

Prove the well known resummation of the geometric series:
%%
    \begin{equation}\label{eq:SW_0}
         1 + x + x^2 + x^3 + \dots =  \frac{1}{1-x} \quad \text{for } |x| < 1
    \end{equation}
%%
can be analytically continued to $|x| \geq 1$ with the Sommerfeld-Watson Transform.

Assume that $|x| > 1$ and show that the summation can be written as an integral over the complex plane
%%
    \begin{equation}
        \label{eq:SW_1}
         \int \frac{d\ell}{2i} \frac{(-x)^\ell}{\sin \pi \ell} = 1 + x + x^2 + \dots ~.
    \end{equation}
%%
Draw the contour around which the above integration should be taken (careful with orientations and signs).
Deform the contour such that you can relate \cref{eq:SW_1} to the series
%%
    \begin{equation}
        \frac{1}{x} + \frac{1}{x^2} + \frac{1}{x^3} + \dots = \frac{1}{1- \frac{1}{x}}
    \end{equation}
%%
and arrive at \cref{eq:SW_0}.

\subsection{Van Hove Reggeon}
Revisit the Regge behavior of \cref{eq:vanhove} using the S-W transform. How does the inclusion of poles at $\alpha(s) = \ell$ change the contour of integration and the leading contribution to the asymptotic behavior?

\section{Finite Energy Sum Rules}
Consider $z$ a complex variable and $\alpha$ a real fixed parameter. What is the analytic structure of the function $z^\alpha$? What is the discontinuity across the cut?

Write a Cauchy contour $C$ surrounding the cut and closing it with a circle of radius $\Lambda$ in the complex $z$ plane, and check that 
\begin{align}
    \oint_{C} z^\alpha \mathrm d z & = 0
\end{align}

You can start with the simple case $\alpha = 1/2$, {\it i.e.} $\sqrt{z}$, then generalize to any real $\alpha$. 

\bibliographystyle{apsrev4-2.bst}
\bibliography{biblio}

\newpage
\begin{center}
    SOLUTIONS
\end{center}

% \section{Crossing and $t$-channel kinematics}
% 
\noindent In this sheet we will consider the elastic scattering of two identical, spinless particles with 4-momentum $q_{i}$ and with mass $q_i^2 = m^2$. 
 We define the usual Mandelstam variables 
 %%
    \begin{gather}
        s = (q_1 + q_2)^2 = (q_3 + q_4)^2 \nonumber\\
        t = (q_1 - q_3)^2 = (q_4 - q_2)^2 \nonumber \\
        u = (q_1 - q_4)^2 = (q_2 - q_3)^2 \nonumber
    \end{gather}
 %%
We refer to the $s$-channel as the physical region describing the process 
%%
    \begin{equation}
        1 \, (q_1) + 2 \, (q_2) \to 3 \, (q_3) + 4 \, (q_4) ~, \nonumber
    \end{equation}
%%
while in the $t$-channel we consider
    \begin{equation}
            1 \, (q_1) + \bar{3} \, (q_{\bar{3}}) 
            \to  \bar{2} \, (q_{\bar{2}}) + 4 \, (q_4) ~. \nonumber
    \end{equation}
%%
    
\section{Reggeons and Unitarity}

\subsection{Elementary $t$-channel exchanges}
The $J=0$ is trivial
\begin{equation}
    A^0(s,t) = i \, g_0 \, \frac{1}{m_0^2 - t} = i \, g_0 \, \frac{P_0(\cos\theta_t)}{m_0^2 - t} ~.
\end{equation}
For $J=1$ use $q_1 = (\sqrt{t}/2, q_t \, \hat{z})$ and $q_{\bar{3}} = (\sqrt{t}/2, - q_t \, \hat{z} )$.
In the $t$-channel CM frame we have $k = (q_1 - q_3) = (q_1 + q_{\bar{3}}) = (\sqrt{t}, \vec{0})$ and
%%
    \begin{equation}
        -\tilde{g}_{\mu\nu} =  - g_{\mu\nu} + \frac{k_\mu \, k_\nu}{t}
        =  -\left[\delta_{\mu0} \, \delta_{\nu0} - \delta_{ij} \right] + \frac{\sqrt{t}^2}{t} \, \delta_{\mu0} \, \delta_{\nu0} = +\delta_{ij} ~.
    \end{equation}
%%
thus $q_1^\mu \, \tilde{g}_{\mu\nu} q_{\bar{2}}^\nu =  \vec{q}_1 \, \cdot \, \vec{q}_{\bar{2}} = q_t^2 \, \cos\theta_t$. Similarly $q_1^\mu \, \tilde{g}_{\mu\nu} q_{1}^\nu =  q_{\bar{2}}^\mu \, \tilde{g}_{\mu\nu} q_{\bar{2}}^\nu  = q_t^2$ and we have
%
    \begin{equation}
        A^1(s,t) = i g_1 \, q_t^2 \frac{ \cos\theta_t}{m_1^2 - t} = i g_1 \, q_t^2 \frac{P_1(\cos\theta_t)}{m_1^2 - t} ~,
    \end{equation}
%%
and finally also
%%
    \begin{equation}
        A^2(s,t) = i g_2 \, q_t^4 \,\frac{\frac{1}{2}(3 \cos\theta_t - 1)}{m_2^2 - t} =  i g_2 \, q_t^4 \, \frac{ P_2(\cos\theta_t)}{m_2^2 - t} ~.
    \end{equation}
%%
The generalization to arbitrary $J$ is
%%
    \begin{equation}
        A^J(s,t) = ig_J \, q_t^{2J} \, \frac{ P_J(\cos\theta_t)}{m_J^2 - t} ~.
    \end{equation}
%%

\subsection{Unitarity vs Elementary exchanges}
We have 
%%
    \begin{equation}
    \sigma_\text{tot} = \left. \frac{1}{2q\sqrt{s}} \, \frac{g_J}{m_J^2} \, q_t^{2J} \, P_J(\cos\theta_t)  \right |_{t=0} ~.
    \end{equation}
%%
We have $q_t^2 \, \cos\theta_t = (s-u)/ 4$ so that as $s\to \infty$, we have:
%%
    \begin{equation}
        \sigma_\text{tot} \sim s^{J-1} ~.
    \end{equation}
%%
To satisfy the Froissart bound, the maximally allowed spin then is $J=1$. 

\subsection{Van Hove Reggeon}

We can write
%%
    \begin{equation}
        J-\alpha(t) = J - \alpha(0) - \alpha^\prime \, t = \alpha^\prime \left( (J-\alpha(0))/\alpha' - t\right) 
    \end{equation}
%5
and thus we have $m_J^2 = (J-\alpha(0))/\alpha^\prime$. 

We can use 
%%
    \begin{align}
        (\cos\theta_t)^J  &= \sum_{J+J^\prime \text{ even}}^J \frac{(J+1)!}{(J-J')!! \, (J+J'+1)!!} \, P_{J'}(\cos\theta_t) \\
        &= \sum_{J+J^\prime \text{ even}}^J \mu_{JJ'} \, P_{J'}(\cos\theta_t)
    \end{align}
%%
to write
%%
    \begin{align}
        A(s,t) &= \sum_J \, \sum_{J'=0}^J \left(\frac{g \, r^{2J} \mu_{JJ'}}{\alpha'}\right) q_t^{2J} \, \frac{P_{J'}(\cos\theta_t)}{m_J^2 - t} ~,
        \\
        &= \sum_J \, \sum_{J'=0}^J g_{JJ'} \, q_t^{2J} \, \frac{P_{J'}(\cos\theta_t)}{m_J^2 - t} ~,
    \end{align}
%%
Comparing with the form of our elementary exchanges, this amplitude is an infinite sum of particles with spin-$J$ and mass $m_J^2$ but also all same parity daughters at the same mass. 

If the sum is truncated at $J_\text{max}$ the $s\to\infty$ limit is dominated by the largest spin exchange and we have $A_\text{trunc}(s,t) \propto s^{J_\text{max}}$. 

\subsection{Analytic continuation in $J$}
Go back to the original form in terms of monomials, we can write
%%
    \begin{equation}
A(s,t) = \sum_{J=0} \int_0^1 dx \, g \, r^{2J} (q_t^2 \, \cos\theta_t)^J \, x^{J-\alpha(t)-1} ~.
    \end{equation}
%%  
Collecting all things with powers of $J$, we notice a geometric series which can be summed analytically
%%
    \begin{equation}
        A(s,t) = g \,\int_0^1 dx \, \frac{x^{-\alpha(t) -1}}{1 - r^2 \, q_t^2 \, \cos\theta_t \, x} ~.
    \end{equation}
%%
Comparing with the definition of the hypergeometric function, we can identify $z = r^2 \, q_t^2 \, \cos\theta_t$ and $b = -\alpha(t)$. Since there is no $(1-x)$ term we require $c = b+1= 1-\alpha(t)$. Thus we have
%5
    \begin{align}
        A(s,t) &= \frac{ \Gamma(-\alpha(t))}{\Gamma(1-\alpha(t))} \, _2F_1\left(1,-\alpha(t), 1-\alpha(t), (q_t \,r)^2 \, \cos\theta_t \right)
        \\
        &= \Gamma(-\alpha(t)) \,  _2\tilde{F}_1\left(1,-\alpha(t), 1-\alpha(t), (q_t \,r)^2 \, \cos\theta_t \right) ~.
    \end{align}
%%

\subsection{Unitarity vs Reggeized exchanges} 
From the hypergeometric form we can take $s\to \infty$ which takes $q_t^2 \, \cos\theta_t = (s-u)/4 \to \infty$ and we can write
%%
    \begin{equation}
        A(s,t) = g_0 \, \Gamma(-\alpha(t)) \, \Gamma(1+\alpha(t)) \, \left(\frac{u-s}{4r^{-2}}\right)^{\alpha(t)} ~.
    \end{equation}
%%
So, we have
%%
    \begin{equation}
        \Im A(s,0) \propto \Im (-s)^{\alpha(0)} \propto \sin \pi \alpha(0) \, s^{\alpha(0)}
    \end{equation}
%%
so $\sigma_\text{tot} \sim s^{\alpha(0)-1}$ and unitarity requires $\alpha(0) \leq 1$.
 
\subsection{The Reggeon ``propagator"}
As we see above, switching $s\leftrightarrow u$ introduces a minus sign and we have 
%%
    \begin{equation}
        A^\pm(s,t) = g_0 \, \Gamma(1+\alpha(t)) \, \frac{1}{2}[\pm1 + e^{-i\pi\alpha(t)}] \, \Gamma(-\alpha(t)) \left(\frac{s-u}{4r^{-2}}\right)^{\alpha(t)} ~,
    \end{equation}
%%
and we can read off $\beta(t) = g_0 \, \Gamma(1+\alpha(t))$. Using $s \sim -u$ we also see $s_0 = 2 \, r^{-2}$

\section{Veneziano Amplitude}
\subsection{Duality}
We can write:
%%
    \begin{equation}
        V(s,t) = (1-\alpha(s) - \alpha(t)) \, B(1-\alpha(s), 1-\alpha(t)) ~.
    \end{equation}
%%
Then using the expansion of the Beta function on its first argument, we have
%%
    \begin{equation}
        V(s,t) = (1-\alpha(s) - \alpha(t)) \, \sum_{J=1}^\infty \, \frac{\Gamma(J-1+\alpha(t))}{\Gamma(J) \, \Gamma(\alpha(t))} \, \frac{1}{J-\alpha(s)}
    \end{equation}
%%
which only has poles in $\alpha(s)$. Because of the $s\leftrightarrow t$ symmetry, we can write the exact same expression with only poles in $\alpha(t)$.

\subsection{Isospin basis}
We have:
%%
    \begin{gather}
         \mathcal{A}^{(0)}(s,t,u) = \frac{1}{2} \left[ 3 \, V(s,t) + 3\,V(s,u) - V(t,u)\right] \\
         \mathcal{A}^{(1)}(s,t,u) = V(s,t) - V(s,u) \\
         \mathcal{A}^{(2)}(s,t,u) = V(t,u) ~.
    \end{gather}
%%
$I=0,2$ are symmetric in $t\leftrightarrow u$ while $I=1$ is anti-symmetric as required by Bose symmetry. 

\subsection{Chew-Frautshi plot}
A single $V(s,t)$ will have poles at all $\alpha(s) = J\geq 1$ and all possible daughters. The residues are 
%%  
    \begin{equation}
        - (J-1+\alpha(t)) \, \frac{\Gamma(J-1+\alpha(t))}{\Gamma(J) \, \Gamma(\alpha(t))} = \frac{-1}{\Gamma(J)} \frac{\Gamma(J+\alpha(t))}{\Gamma(\alpha(t))} = - \frac{(\alpha(t))_J}{(J-1)!}.
    \end{equation}
%%
For a linear trajectory this is a order $J$ polynomial in $t$ and therefore in $z_s$. 

The symmetry factors in $I=0,1$ will remove all odd (even) $J$ daughters. The $I=2$ amplitude has no $s$ dependence and therefore no isospin-2 poles at all.

\subsection{Regge limit}
Starting with 
    \begin{equation}
        V(s,t)  \to \Gamma(1-\alpha(s)) \, (-\alpha(t))^{\alpha(s)} \sim \Gamma(1-\alpha(s)) \, \left(-\alpha^\prime \, t\right)^{\alpha(s)} ~.
    \end{equation}
Similarly 
        \begin{equation}
        V(s,u)  \to \Gamma(1-\alpha(s)) \, (-\alpha(u))^{\alpha(s)} \sim \Gamma(1-\alpha(s)) \, \left(-\alpha^\prime \, t\right)^{\alpha(s)} ~.
    \end{equation}
Thus the combination 
%%
    \begin{align}
        V(s,t) \pm V(s,u) &\to \Gamma(1-\alpha(s)) \times \left[\left(-\alpha^\prime \, t\right)^{\alpha(s)} \pm \left(-\alpha^\prime \, u\right)^{\alpha(s)} \right] \\
        &= \Gamma(1-\alpha(s)) \times \left[1\pm e^{-i\pi\alpha(s)}\right] \, \left(\alpha^\prime \, t\right)^{\alpha(s)}
    \end{align}
%%

\subsection{Ancestors}
If we allow $\alpha(t)$ to be complex, then at a pole $\alpha(s) \to J + i \Gamma$ and the residue we calculated
    \begin{equation}
        \frac{\Gamma(J+i \,\Gamma + \alpha(t))}{\Gamma(\alpha(t))} ~,
    \end{equation}
is no longer a fixed order polynomial in $t$. It will thus give contributions to ALL spins at each pole, i.e. introduce an infinite number of ancestors. Similarly if $\alpha(s)$ is non-linear, we will have finitely many ancestors but still unphysical poles nonetheless.

This means the Veneziano amplitude \textit{only} gives a physical picture for real and linear trajectories. This means we require $J \propto s \sim m^2$ which mimics the spectrum of states in a relativistic rotating string. This gives rise to the stringy picture of a $q\bar{q}$ pair connected by a gluon flux tube and later the entire field of string theories. 
\section{Sommerfeld-Watson Transform}
\subsection{Geometric series}
We want to show that we can analytically continue the geometric series to $|x|>1$ using the Sommerfeld-Watson Transform.

First, we will prove that the sum can be written as an integral over the complex plane:
\begin{equation}
    \int_C\frac{d\ell}{2i}\frac{(-x)^\ell}{\sin\pi\ell} \ ,
\end{equation}
where the function $1/\sin\pi\ell$ has poles at integer values of $\ell=\ldots, -2,-1,0,1,2,\ldots$
We use the Cauchy Residue Theorem:
\begin{equation}
    \oint f(z) dz = \pm 2\pi i \sum_{k}\textrm{Res}_{z=z_k}f(z) \ ,
\end{equation}
with sign $+$ for a counterclockwise contour and $-$ for a clockwise contour around the pole at $z_k$. 
The residue of $f(\ell)=(-x)^\ell/\sin\pi\ell$ at $\ell=k$ is given by
\begin{equation}
    \textrm{Res}_{\ell=k}\frac{(-x)^\ell}{\sin\pi\ell}=\lim_{\ell\to k}(\ell-k)\frac{(-x)^\ell}{\sin\pi\ell}=\lim_{\ell\to k}\frac{(-x)^\ell}{\pi\cos\pi\ell}=\frac{x^k}{\pi}
\end{equation}
Therefore, if we encircle all the poles at $\ell=k$ for $k\geq 0$ with counterclockwise contours $C_k$, which we can combine to a single counterclockwise contour $C$ encircling all the poles at $0$ and positive integers, we obtain the geometric series:
\begin{equation}
    \sum_{k=0}^\infty\int_{C_k}\frac{d\ell}{2i}\frac{(-x)^\ell}{\sin\pi\ell}=\int_C\frac{d\ell}{2i}\frac{(-x)^\ell}{\sin\pi\ell}=\sum_{k=0}^\infty x^k=1+x+x^2+\cdots
\end{equation}

Next, we deform the contour to a vertical line from $\sigma+i\infty$ to $\sigma-i\infty$, with $-1<\sigma<0$, and further deform it to enclose all negative integers in a clockwise contour $C'$, that we can split in individual clockwise contours $C_{k'}$:
\begin{align}
    \int_{C'}\frac{d\ell}{2i}\frac{(-x)^\ell}{\sin\pi\ell}&=\sum_{C_{k'}}\int_{C_{k'}}\frac{d\ell}{2i}\frac{(-x)^\ell}{\sin\pi\ell}=-\frac{1}{x}-\frac{1}{x^2}-\frac{1}{x^3}-\cdots \\
    & =-\frac{1}{x}\left(1+\frac{1}{x}+\frac{1}{x^2}+\cdots\right)    \nonumber 
\end{align}
and given the assumption $|x|>0$, we have $|1/x|<1$, and we can sum the geometric series:
\begin{equation}
    -\frac{1}{x}\left(1+\frac{1}{x}+\frac{1}{x^2}+\cdots\right)    = -\frac{1}{x}\frac{1}{1-\frac{1}{x}}=\frac{1}{1-x} \ .
\end{equation}

\subsection{Van Hove Reggeon}
If we include a Regge pole $[\ell-\alpha(t)]^{-1}$, in the process of deforming the contour from $C$ to $C'$ we have to pick the residue of the pole at $\ell=\alpha(t)$, with $\textrm{Re}\,\alpha(t)<0$. This means we have an extra clockwise contour $C_\alpha$, from which we obtain an extra contribution $\propto x^{\alpha(t)}$. Since $x \sim q_t^2 \, z_t \sim s$ this yields the $s^{\alpha(t)}$ behavior.

\section{Finite Energy Sum Rules}
The function $z^\alpha$ has a branch cut for $z\in [-\infty, 0]$. The Cauchy contour enclose the cut and the discontinuity across that cut is
\bsub\begin{align}
    (z+i\epsilon)^\alpha - (z-i\epsilon)^\alpha & =  (|z| e^{i \pi})^\alpha- (|z| e^{-i \pi})^\alpha & \text{for real negative} z
    \\
    &= |z|^\alpha \left( e^{i\pi \alpha} - e^{-i\pi \alpha}  \right)
    \\
    & = 2 i |z|^\alpha \sin \pi \alpha
\end{align}\esub
The Cauchy contour is then, with $C_\Lambda$ being the circle of radius $\Lambda$ in the positive sense,
\bsub\begin{align}
    \oint z^\alpha \mathrm d z & = \int_{-\Lambda}^0 (z+i \epsilon)^\alpha \mathrm d z + \int^{-\Lambda}_0 (z-i \epsilon)^\alpha \mathrm d z + \oint_{C_\Lambda} z^\alpha \mathrm d z
    \\
    & = 2i \sin \pi \alpha \int_{-\Lambda}^0 |z|^\alpha \mathrm d z + \oint_{C_\Lambda} z^\alpha \mathrm d z
\end{align}\esub
The first integral is easily done
\begin{align}
    2i \sin \pi \alpha \int_{-\Lambda}^0 |z|^\alpha \mathrm d z & = \frac{2i \Lambda^{\alpha+1}}{\alpha+1} \sin \pi \alpha.
\end{align}
For the second integral, we need the change of variable $z = \Lambda \exp(i \theta)$, with $\theta \in [-\pi,\pi]$. We obtain
\bsub\begin{align}
     \oint_{C_\Lambda} z^\alpha \mathrm d z & = 
     i\Lambda^{\alpha+1} \int_{-\pi}^\pi e^{i \theta(\alpha+1)} \mathrm d \theta =  \frac{i\Lambda^{\alpha+1}}{\alpha+1}
     \left(e^{i \pi(\alpha+1)} -e^{-i \pi(\alpha+1)} \right)
     \\
     & = - \frac{2i \Lambda^{\alpha+1}}{\alpha+1} \sin \pi \alpha 
\end{align}\esub
We used $\exp(i\pi) = -1$. 

\end{document}

**Comment by mmikhasenko** [comment]
Closed by #46
